wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 200
log_interval:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.01
momentum:
  desc: null
  value: 0.6
no_cuda:
  desc: null
  value: false
seed:
  desc: null
  value: 42
test_batch_size:
  desc: null
  value: 64
